### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by dobladez**
I implemented a "defmojo" macro to make it cleaner/easier to write a mojo.
I wasn't convinced that the "mojo-annotations" project was the right place for this... but I didn't want to create another subproject just for defmojo.

I also fixed what looked like a typo on the clojars repo URL.

Let me know what you think. I'm pretty new to clojure.

Thanks for the great work.
Fer

### CODE REVIEW

**Comment by hugoduncan** [comment]
hey, looks interesting.  There is something similar in https://github.com/pallet/zi/blob/develop/src/main/clojure/zi/mojo.clj which I have been planning forever to put back into clojure-maven. Looks like there are a couple of differences in implementation, so I'll have to consider which bits to take. The use of keywords for the annotation types looks useful, as does the parameter mapping.

Are there any functions other than `execute` that need implementing in a plugin?

**Comment by dobladez** [comment]
Oops, I missed your existing defmojo.  And yes, one on my goals was to avoid exposing the Java annotations to the user of defmojo.
If we define a simple convention for transforming the names, we could replace the `keyword-to-java` map (line 13) with a transformation function.

> Are there any functions other than execute that need implementing in a plugin?

I don't think so. The `Mojo` interface only declares `setLog` (which defmojo implements for you) and `execute`.

**Comment by hugoduncan** [comment]
I've added a new sub-project for this and included zi.log which I think belongs here too.

If you can address the comments, and also ensure lines are less than 80 chars long, that would  be fantastic!

@timclemons do you have any comments?

**Comment by dobladez** [comment]
Sounds good. I'll try to squeeze some free time this week to address those issues and send you a new pull request.

Thanks Hugo.

**Comment by dobladez** [comment]
Just sent a new pull request with the suggested changes.

**Comment by timclemons** [comment]
@hugoduncan Sorry, late to the party.  It makes sense to move this and the logging stuff out of zi and into clojure-maven.  I've looked over the pull-request that follows this one and my only concern is that there doesn't appear to be an explicit means of including Plexus components.  This is functionality I depend on in the old implementation.

**Comment by dobladez** [comment]
@timclemons I see... I didn't even know about Plexus components... Let's come up with syntax to accommodate that.

Example1:

```
(defmojo Mojure
  "This is a Mojo in Clojure"
  {:goal "simple" :phase "validate"}     
  [:parameters
   base-directory   {:expression "${basedir}" :required true :description "Base project Directory"}
   project          {:expression "${project}" :required true :readonly true}]
  [:components
   compX   {:role "xxx.yyy.Zzzz}"]

  (log/info (str "Hello World!")))
```

I now think it's more idiomatic to remove the maps, right?

Also, we could allow a "docstring" for parameter (like the original defmojo you had in place).
With those two it'd read something like:

Example2:

```
(defmojo Mojure
  "This is a Mojo in Clojure"
  {:goal "simple" :phase "validate"}

 [:parameters
  base-directory "Base project Directory" :expression "${basedir}" :required true
  project                                 :expression "${project}" :required true :readonly true]

 [:components
   compX   {:role "xxx.yyy.Zzzz}"]

  (log/info (str "Hello World!")))
```

any better ideas? I'd be happy to make the changes one we agree on the syntax.
Thanks again.

**Comment by timclemons** [comment]
I agree that removing the maps would be more consistent with how other macros, such as `ns`, work in Clojure.  In fact, modeling how `ns` handles `:use` and `:require` would be a viable approach, making each parameter or component definition it's own nested vector:

``` clojure
(defmojo Mojure
  "This is a Mojo in Clojure"
  {:goal "simple" :phase "validate"}

  [:parameters
    [base-directory "Base project Directory" :expression "${basedir}" :required true]
    [project :expression "${project}" :required true :readonly true]]

  [:components
    [compX :role "xxx.yyy.Zzzz"]]

  (log/info (str "Hello World!")))
```

Let me know your thoughts.

**Comment by dobladez** [comment]
I see. I'd say that if we put vectors on each param, then we probably don't need a vector around all of them.
However, as you say, the ns macro (or uses of it at least) does have that grouping, using lists instead of vectors for some reason.

Also, we could remove the map from the fist set of flags. Here's what I mean:

```(defmojo Mojure "This is a Mojo in Clojure"
  :goal "simple"
  :phase "validate"
  :parameters
    [base-directory "Base project Directory" :expression "${basedir}" :required true]
    [project :expression "${project}" :required true :readonly true]
  :components
    [compX :role "xxx.yyy.Zzzz"]

 (log/info (str "Hello World!")))

Honestly, I'm not 100% convinced of using vectors in "key-value" scenarios like this, but it seems to be idiomatic in Clojure... so let's go for it.

**Comment by hugoduncan** [comment]
Explicit maps aren't bad.

``` clj
(defmojo Mojure
  "This is a Mojo in Clojure"
  {:goal "simple"
   :phase "validate"}
  {:parameters
     {base-directory {:expression "${basedir}" :required true
                      :description "Base project Directory"}
      project        {:expression "${project}" :required true :readonly true}}
   :components
      {compX   {:role "xxx.yyy.Zzzz}"}}

  (log/info (str "Hello World!")))
```

The use of a map for :goal and :phase is reminiscent of metadata on `defn` and
`defmacro`. The second map introduce symbols available in the body, however, so
might be better as something more arglist like.

``` clj
(defmojo Mojure
  "This is a Mojo in Clojure"
  {:goal "simple"
   :phase "validate"}
  [:parameters
     {base-directory {:expression "${basedir}" :required true
                      :description "Base project Directory"}
      project        {:expression "${project}" :required true :readonly true}}
   :components
      {compX   {:role "xxx.yyy.Zzzz}"}]

  (log/info (str "Hello World!")))
```

I think the component can be inferred from the :role attribute, so:

``` clj
(defmojo Mojure
  "This is a Mojo in Clojure"
  {:goal "simple"
   :phase "validate"}
  [base-directory {:expression "${basedir}" :required true
                   :description "Base project Directory"}
   project {:expression "${project}" :required true :readonly true}
   compX {:role "xxx.yyy.Zzzz"}]

  (log/info (str "Hello World!")))
```

or

``` clj
(defmojo Mojure
  "This is a Mojo in Clojure"
  {:goal "simple"
   :phase "validate"}
  [^{:expression "${basedir}" :required true
     :description "Base project Directory"} base-directory
   ^{:expression "${project}" :required true :readonly true} project
   ^{:role "xxx.yyy.Zzzz"} compX]

  (log/info (str "Hello World!")))
```

**Comment by timclemons** [comment]
The `:role` argument is actually optional, so better to explicitly state that it's a component.

**Comment by hugoduncan** [comment]
I'm not convinced the `:role` is optional in clojure, since the field has no intrinsic type on which plexus can infer the component role.

**Comment by dobladez** [comment]
Hugo: from your proposals, the one I'd prefer is the second to last. The first ones have too many nested {}/[]s, and I don't like the metadata syntax on the last one.

If we decide to make `parameters` and `component` explicit, then I personally like them to be in the same collection as `:goal`, `:phase`, etc.. Like:

``` clojure
(defmojo Mojure "This is a Mojo in Clojure"
  {:goal "simple"
   :phase "validate"
   :parameters
      [base-directory "Base project Directory" :expression "${basedir}" :required true]
      [project :expression "${project}" :required true :readonly true]
    :components
      [compX :role "xxx.yyy.Zzzz"] }
   (log/info (str "Hello World!")))
```

again, here I'm not using a map for the flags of each parameters, consistent with the [coding standards](http://dev.clojure.org/display/design/Library+Coding+Standards)

**Pull request closed without merging**
